### ISSUE TITLE
Issue on geocoder side when using header with a column named geocoder__line

### ISSUE THREAD

**Issue by ThomasG77** [jdesboeufs/addok-geocode-stream#17]
How can I affirm this?

See my commit that described what happen at https://github.com/ThomasG77/addok-geocode-stream/commit/dcabb3d56ce1170b03099c8ae3e6525a6eb4813a and also reference a gist to reproduce the issue on the server side. In the gist, we demonstrate the issue only using curl and playing with csv with different headers name.

The fix is done on the client side as the column `geocoder__line` disappearance makes the code failing later and the renamed column does not appear in the end result.

What is more annoying is we got not idea why this behaviour happens on server side.

I can also make a PR using my commit, depending of your feedback. In this case, I will also change code in the tests https://github.com/jdesboeufs/addok-geocode-stream/blob/f312f219ecfedb3a87e34a461228cea308e8dc20/lib/__tests__/geocode.js

**Comment by ThomasG77** [comment]
In fact, same issue as https://github.com/jdesboeufs/addok-geocode-stream/pull/12 but solved with another way than mine

**Comment by jdesboeufs** [comment]
There were an error in our production cluster configuration.

We use https://github.com/BaseAdresseNationale/api-geocode which uses this project.
But we didn't define the `GEOCODER_COLUMN_PREFIX` environment variable, so local `addok-geocode-stream` was in conflict with the remote one.

Thank you! 🙆‍♂️
